google/gnxi

- utils/credentials/credentials.go
Add insecure flag to allow users to bypass TLS validation.
> Add insecure flag to skip tls validation

- gnmi/server.go
>  Fix gNMI_target JSON encoding

- gnmi_get/gnmi_get.go
Adds the ability to ask the target for a specific set of models to be used when replying to a GetRequest message.
> Add UseModels to getRequest

- gnmi_set/gnmi_set.go
- utils/xpath/path.go
Checked for ':' in path attribute
> Added support for parsing the origin in the Path.

- gnmi_set/gnmi_set.go
- utils/xpath/path.go
Reverting google/gnxi#38 due to google/gnxi#43
> Revert "Added support for parsing the origin in the Path."

- gnmi_cli_py/README.md
- gnmi_cli_py/py_gnmicli.py
Add SetRequest Update/Replace/Delete. Support for dumping val as JSON.
Updated README with examples.
> Add SetRequest Update/Replace/Delete. Support for dumping val as JSON.

- gnmi_cli_py/README.md
- gnmi_cli_py/py_gnmicli.py
Deal with self-signed and publicly signed Target certificates.
> Fix certificate handling.

- gnmi_cli_py/py_gnmicli.py
This commit will fix issue https://github.com/google/gnxi/issues/52
> Issue 52 Fix

- gnmi_cli_py/.gitignore
- gnmi_cli_py/README.md
- gnmi_cli_py/requirements.txt
* Adds a python virtualenv 'requirements.txt' file for dependencies
* Updates the README with virtualenv how-to's
* Adds .gitignore for python files
> Feature: Add support for python virtualenv

- gnmi_cli_py/README.md
- gnmi_cli_py/py_gnmicli.py
Adding the notls option for the python gnmi client (might have some use in isolated lab environments).
> 	modified:   py_gnmicli.py

- gnmi_cli_py/Dockerfile
- gnmi_cli_py/README.md
- gnmi_cli_py/py_gnmicli.py
*Fix set-delete operation.
*Add Dockerfile.
*Update README to include Docker instructions.
> Issue #62 & add Docker

- gnmi_cli_py/py_gnmicli.py
Add ability to print GetResponse if response is string_val.
> Add printing of str_val in GetResponse.

- gnoi_reset/README.md
- gnoi_reset/gnoi_reset.go
Refers to Issue #97
Added README.md and gnoi_reset client binary (based on gNMI binaries)
> gNOI Reset Client Binary and README

- gnmi_capabilities/README.md
- gnmi_capabilities/gnmi_capabilities.go
- gnmi_get/README.md
- gnmi_get/gnmi_get.go
- gnmi_set/README.md
- gnmi_set/gnmi_set.go
- gnmi_target/README.md
- gnmi_target/gnmi_target.go
- gnoi_cert/README.md
- gnoi_cert/gnoi_cert.go
- gnoi_target/README.md
- gnoi_target/gnoi_target.go
> Update to standard gNMI/gNOI port

- certs/README.md
- certs/generate.sh
Related Issue: Closes #93 
Added script to generate certs from the link provided in the related issue :)
> Added script to generate certs

- .travis.yml
- gnoi/os/manager_test.go
> Added tests for os manager

- gnoi/gnoi.go
- gnoi/gnoi_test.go
- gnoi/os/manager.go
- gnoi/os/server.go
- gnoi/os/server_test.go
- gnoi_target/gnoi_target.go
Related issue: Closes #113 
Added OS Activate service and tests
> OS Activate Target

- gnoi/cert/client.go
- gnoi/os/client.go
- gnoi/os/server_test.go
- gnoi/reset/client.go
- utils/utils.go
Closes #120 
Utils has a new LogProto function and a new log_proto flag
> Added Proto Logging for gNOI OS, Cert and Reset

- gnoi/os/client.go
- gnoi/os/client_test.go
> Added Verify RPC call for OS client

- gnoi/os/client.go
- gnoi_os/gnoi_os.go
Added Verify RPC to client and added logging
> Added logging to Verify client RPC

- gnoi_cert/gnoi_cert.go
- utils/credentials/credentials.go
> Refactored gnoi_cert for use with client cert + key

- gnoi/os/client_test.go
- gnoi/os/manager_test.go
> Added unit test for OS client Install

- gnoi_os/gnoi_os.go
> Added OS install RPC to binary

- gnoi/cert/manager.go
- gnoi/cert/manager_test.go
- gnoi/cert/server.go
- gnoi/gnoi.go
- gnoi/gnoi_test.go
- gnoi_target/gnoi_target.go
- utils/credentials/credentials.go
> Added certificate refactor to gnoi_target

- gnoi/os/server.go
- utils/mockos/mockos.go
- utils/mockos/mockos_test.go
> Tests for MockOS

- gnoi/os/server_test.go
> Install Target Tests

- gnoi/cert/client.go
- gnoi/cert/client_test.go
- gnoi/cert/server.go
> Added tests for Rotate Cert Client RPC

- gnoi/reset/client_test.go
Increase test coverage for gNOI Reset
> Added test for ResetTarget

- gnoi/cert/client.go
- gnoi/cert/client_test.go
- gnoi/cert/manager.go
> Full test coverage for gnoi/cert/client.go

- gnxi_tester/config/config.go
- gnxi_tester/config/config_test.go
- gnxi_tester/config/defaults.go
Closes #170
Adjusted GetTests to fix interface conversion
Tests should be executed in the order:
Cert, OS, Reset
> Added Default Tests

- gnxi_tester/cmd/run.go
- gnxi_tester/config/defaults.go
- gnxi_tester/orchestrator/containers.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
> Added Orchestrator Logic

- gnxi_tester/orchestrator/containers.go
- gnxi_tester/orchestrator/containers_test.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
- go.mod
- go.sum
> Added InitContainers for docker aspect of orchestrator

- gnoi/cert/server.go
- gnoi/cert/server_test.go
> Added tests for gnoi/cert/server.Install

- gnxi_tester/config/config.go
- gnxi_tester/config/defaults.go
- gnxi_tester/config/dockerfiles.go
- gnxi_tester/config/dockerfiles_test.go
This will dynamically generate the dockerfiles in the .gnxi directory in the users home. They are needed since the docker sdk needs a path to a dockerfile to build a new image on the host system
> Added dockerfiles to config

- gnxi_tester/config/defaults_test.go
> Fix for defaults_test.go

- gnxi_tester/config/defaults.go
> Changed regex in default tests

- gnmi_subscribe/gnmi_subscribe.go
Re: Issue #192 
This PR sets up flags, path parsing and constructs the initial SubscribeRequest
> gNMI Subscribe Client Setup

- gnoi/os/manager.go
- gnoi/os/server.go
- gnoi/os/server_test.go
- gnoi_os/gnoi_os.go
- gnxi_tester/config/defaults.go
Closes #203 
Force transferring OS is now possible
Errors if it is the currently running OS
> -version flag is optional

- gnxi_tester/cmd/run.go
- gnxi_tester/config/config.go
- gnxi_tester/config/config_test.go
- gnxi_tester/config/defaults.go
- gnxi_tester/orchestrator/containers.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
It should all be working now.
Related issues: Closes #163 Closes #166
> Finalized orchestrator CLI 

- gnxi_tester/cmd/web.go
- gnxi_tester/config/defaults.go
- gnxi_tester/config/web.go
- gnxi_tester/config/web_test.go
- gnxi_tester/web/config.go
- gnxi_tester/web/file.go
- gnxi_tester/web/prompts.go
- gnxi_tester/web/prompts_test.go
- gnxi_tester/web/routes.go
- gnxi_tester/web/run.go
- gnxi_tester/web/upload.go
- go.mod
- go.sum
Related issue: #194
- Added routes and view stubs for all views that will have to be implemented.
- Implemented logic and unit tests for `/prompts`. This will allow the user to store prompt answers in the backend.
> Added Web API stubs.

- gnmi_subscribe/gnmi_subscribe.go
> gNMI Subscribe Client Functionality

- certs/generate.sh
- gnoi/cert/manager.go
- gnoi_target/gnoi_target.go
- utils/entity/entity.go
> Added Subject Alternative Names to cert generation and management

- gnxi_tester/config/history.go
- gnxi_tester/web/routes.go
- gnxi_tester/web/run.go
- gnxi_tester/web/target.go
- gnxi_tester/web/target_test.go
> Added Target Endpoints for web API

- gnxi_tester/web/file.go
> Upload and Delete API Functionality

- gnmi_subscribe/gnmi_subscribe_test.go
> Tests for gNMI Subscribe Client

- gnxi_tester/README.md
> Added documentation for gnxi_tester

- gnmi_cli_py/py_gnmicli.py
> Fix path parsing so / works in xpaths

- gnxi_tester/config/config.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/web/routes.go
- gnxi_tester/web/tests.go
- gnxi_tester/web_ui/src/app/app.module.ts
- gnxi_tester/web_ui/src/app/run/run.component.css
- gnxi_tester/web_ui/src/app/run/run.component.html
- gnxi_tester/web_ui/src/app/run/run.component.ts
- gnxi_tester/web_ui/src/app/test.service.ts
Closes #226
Adds a mat-chip-list to display the list of tests in their default order, this order can be changed and tests can be removed/added
> Order patch

- gnxi_tester/config/config_test.go
- gnxi_tester/config/history_test.go
- gnxi_tester/web/prompts_test.go
- gnxi_tester/web/routes.go
- gnxi_tester/web/target_test.go
- gnxi_tester/web/tests.go
- gnxi_tester/web/tests_test.go
> gnxi_tester Coverage

- gnoi/cert/server_test.go
> Created tests for cert/server.Rotate

- gnxi_tester/web/routes.go
- gnxi_tester/web/routes_test.go
This test walks all routes defined and compares to a list of expected routes
> Added a test to check the routes present on router

- gnoi_cert/gnoi_cert.go
- gnoi_cert/gnoi_cert_test.go
> Add tests for transport functions in gnoi_cert

- gnxi_tester/web/file.go
- gnxi_tester/web/file_test.go
- gnxi_tester/web/routes.go
- go.mod
- go.sum
Adjust files to use afero. This allows the file system to be mocked.
> Added file upload and delete tests

- oc_config_validate/lint.sh
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/requirements.txt
Useful to run before commiting code.
> Add linter script for files in the repo.

- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/testbase.py
The Target was not displayed correctly.
> Correct Null target in STDOUT message and results.

- oc_config_validate/demo/init_config.json
- oc_config_validate/demo/target_config.json
- oc_config_validate/init_configs/example.json
- oc_config_validate/init_configs/interfaces.json
- oc_config_validate/init_configs/subif_static_ip.json
- oc_config_validate/init_configs/system.json
- oc_config_validate/tests/bgp.yaml
- oc_config_validate/tests/interfaces.yaml
- oc_config_validate/tests/lldp.yaml
- oc_config_validate/tests/static_routes_gnmi.yaml
- oc_config_validate/tests/system.yaml
https://datatracker.ietf.org/doc/html/rfc7951#section-4
> Use namespace-qualified top members in JSON text.

- oc_config_validate/docs/testclasses.md
- oc_config_validate/docs/tests.md
- oc_config_validate/lint.sh
- oc_config_validate/oc_config_validate/target.py
- oc_config_validate/oc_config_validate/target_test.py
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/testcases/config_state.py
- oc_config_validate/oc_config_validate/testcases/get.py
- oc_config_validate/oc_config_validate/testcases/setget.py
- oc_config_validate/oc_config_validate/testcases/subif_ip.py
Several changes needed when testing setting and removing ipv4 addresses with real devices.
> Fix oc config validate

- oc_config_validate/oc_config_validate/models/versions
- oc_config_validate/oc_config_validate/update_models.sh
https://github.com/openconfig/public/commit/eabe9951115ddfe310b4913fc429a92732645976
> Add OC model network-instances, where /bgp is now.

- gnmi_subscribe/gnmi_subscribe.go
To support submission of the use_models field via subscribe RPC as per spec
> Add model_data field to subscribe client

- oc_config_validate/lint.sh
- oc_config_validate/oc_config_validate/schema.py
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/testcases/get.py
- oc_config_validate/oc_config_validate/testcases/telemetry_once.py
- oc_config_validate/py_tests/schema_test.py
- oc_config_validate/results/ap_telemetry.json
Add methods for parsing TypedValues, back and forth.
> Improve logging of Subscribe messages

- oc_config_validate/oc_config_validate/target.py
- oc_config_validate/oc_config_validate/testcases/telemetry_sample.py
- oc_config_validate/tests/ap_telemetry.yaml
* Lint corrections
* Use the Exception objects that are directly imported
> Small fixed to oc_config_validate

- oc_config_validate/CONTRIBUTING.md
- oc_config_validate/demo/results.json
- oc_config_validate/demo/run_demo.sh
- oc_config_validate/demo/tests.yaml
- oc_config_validate/lint.sh
- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/py_tests/test_runner.py
- oc_config_validate/py_tests/test_schema.py
Rename and add UnitTests
Update Demo and linting script
Documentation.
> oc_config_validate UnitTests and Scripts

- oc_config_validate/CONTRIBUTING.md
- oc_config_validate/demo/Dockerfile
- oc_config_validate/demo/run_demo.sh
- oc_config_validate/docker/Dockerfile
- oc_config_validate/oc_config_validate/__init__.py
- oc_config_validate/setup.cfg
This also reduces the size of the demo Docker image, by using the gnmi_target built binary.
> Improvements to oc_config_validate PyPi and Docker

- gnmi/server.go
- gnmi/server_test.go
- gnmi_target/gnmi_target.go
Add support for ONCE Subscriptions to gnmi_target.
Based on https://github.com/openconfig/gnmi/blob/master/subscribe/subscribe.go
Attempting to resolve https://github.com/google/gnxi/issues/266 to some extend.
Functionally tested with clients gnmi_target and gnmic.
> gnmi_target supports ONCE Subscriptions

- gnmi/server.go
- gnmi/server_test.go
Add support for Sample STREAM Subscriptions to gnmi_target.
Attempting to resolve https://github.com/google/gnxi/issues/266 to some extend.
Functionally tested with clients gnmi_target and gnmic. Capable of serving multiple subscribers.
> gnmi_target supports Sample STREAM Subscriptions

- oc_config_validate/oc_config_validate/schema.py
Fixes bug introduced in pull/377
> Fix bug in type comparison.

- oc_config_validate/demo/config_tests.yaml
- oc_config_validate/docs/testclasses.md
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/testcases/set.py
- oc_config_validate/oc_config_validate/testcases/setget.py
2nd part of https://github.com/google/gnxi/issues/374
> Add Testcases with Set Replace
