google/gnxi

- gnmi/server.go
The `gnmi/server.go` file uses `doRepaceOrUpdate` rather than `doReplaceOrUpdate` as naming. This PR fixes that typo.
> Fix typo in 'doRepaceOrUpdate' function in gNMI server.

- README.md
- gnmi_target/README.md
- gnmi_target/openconfig-openflow.json
(M) gnmi_target/README.md
-fix the run example (add missing ''\")
(M) README.md
-update main README to include go version requirement.
(M) gnmi_target/openconfig-openflow.json
-Update JSON to include a "state" container. (gnmi_get example fails without this). If this is not appropriate, alternative would be change the gnmi_get
example to use a path of: "/system/openflow/controllers/controller[name=main]/connections/connection[aux-id=0]" (eg leave off the '/state/address')
> Fix readmes and openflow.json

- gnoi/cert/client.go
- Put CertificateId as part of GenerateCSRRequest msg, not LoadCertificateRequest msg.
- For Install and Rotate
Addresses https://github.com/google/gnxi/issues/73
> CertificateId in GenerateCSR instead of LoadCertificateRequest

- utils/entity/entity.go
According to https://tools.ietf.org/html/rfc5280 the pathlen information must be omitted if the CA boolean is false. In this case, since you never assert the CA to be true (hence default false) you must remove the pathlen information.
> Removing pathlen information in accordance with RFC5280 4.2.1.9

- gnoi_cert/gnoi_cert.go
The revoke rpc supports using multiple certificate IDs. This change is to add another argument, `-cert_ids`, that allows a comma separated list of certificate IDs to be passed. The argument is only used by revoke and ignored by other rpcs. The behaviour of `-cert_id` remains unchanged.
Usage:
```
$ alias gnoi_cert
alias gnoi_cert='./gnoi_cert -ca alishar.crt -key alishar.key -target_name gnoi_target -logtostderr'
$ gnoi_cert -op revoke -cert_ids c1,c2,c4
I1009 10:18:36.955688   58961 gnoi_cert.go:210] RevokeCertificates:
{c1: "does not exist",
c4: "does not exist"}
```
Closes https://github.com/google/gnxi/issues/85
> Allow revoke to receive multiple cert ids

- gnoi/reset/client.go
- gnoi_reset/gnoi_reset.go
The client was logging an error even if one wasn't present due to a type mismatch (error vs *ResetError), adjusting the ResetTarget function to return a *ResetError seems to fix this
> Fixed type error, ResetTarget returns a *ResetError

- utils/credentials/credentials.go
Related issue: #108 
This will allow clients that use the library to avail of both options :)
> Refactored credential utils to accept ca.crt, client.crt, client.key or ca.crt, ca.key

- gnoi/os/client_test.go
Install RPC client test is failing since one of the test cases was returning nil. Fixed that.
Closes #145
> Fix for Install test

- gnxi_tester/cmd/run.go
- gnxi_tester/cmd/targets.go
- gnxi_tester/config/config.go
- gnxi_tester/config/config_test.go
- gnxi_tester/config/history.go
Closes #168
Acts as follows:
- If target name and address specified, add to history
- If target name without address:
- Load address already used
- Set address to :9339
- If target without address:
- Use last device
- If no devices in history, error
> Device Connection History

- gnxi_tester/cmd/run.go
- gnxi_tester/cmd/targets.go
- gnxi_tester/config/config.go
- gnxi_tester/config/config_test.go
- gnxi_tester/config/defaults_test.go
- gnxi_tester/config/history.go
- gnxi_tester/config/history_test.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
Removed setting default address
When initially using a target the user must provide the target's name, address, a CA and CA Key
Once added to connection history the user may reuse these details either by specifying the target's name, or entering nothing, then the client will use the last target specified
These details are overwritten if the user specifies the target name and any of the details.
> Added Cert Path to Known Targets

- gnxi_tester/cmd/cmd.go
- gnxi_tester/cmd/run.go
- gnxi_tester/config/defaults.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
Added defaultOrder for default test: provision, cert, os, reset
Surpress log before flag.Parse error
Added order field to config
Provison op decoupled from cert
Refactored runTest to accept a set of tests as an arg
The order can be specified now
When a test isn't specified, the device is provisioned
> Decoupled provision operation from cert

- gnxi_tester/cmd/cmd.go
- gnxi_tester/orchestrator/containers.go
- gnxi_tester/orchestrator/containers_test.go
- gnxi_tester/orchestrator/run.go
Related issue: Close #173
RunContainer will create an exec process in the running container and use it to run the binary with the provided flags. It will then split the standard streams from the process into stdout and stderr and return them separately.
> RunContainer method for orchestrator.

- gnoi/os/client.go
- gnoi/os/client_test.go
- gnoi/os/manager.go
- gnoi/os/server.go
- gnoi/os/server_test.go
- gnoi_os/gnoi_os.go
- gnoi_target/gnoi_target.go
- gnxi_tester/README.md
- gnxi_tester/cmd/run.go
- gnxi_tester/config/defaults.go
- gnxi_tester/orchestrator/containers.go
- gnxi_tester/orchestrator/run.go
- gnxi_tester/orchestrator/run_test.go
- Customisable chunk size for OS transfer in OS service (as previous default was too large and cause a transport error)
- Fixed `--files` in the tester and added a prompt if the user didnt provide the file in `--files`
> Added --files fixes and reduced chunk size in OS Install

- gnmi_capabilities/gnmi_capabilities.go
- gnmi_get/gnmi_get.go
- gnmi_set/gnmi_set.go
- gnmi_subscribe/gnmi_subscribe.go
- gnoi_cert/gnoi_cert.go
- gnoi_os/gnoi_os.go
- gnoi_reset/gnoi_reset.go
- utils/credentials/credentials.go
Closes #169 
TargetName is an exported flag in utils/credentials.go and the server arg is removed from the ClientCredentials functions
> TargetName is an Exported Flag

- gnmi_cli_py/py_gnmicli.py
For example:
/bgp/neighbors/neighbor[neighbor-address=30.1.1.1]/config/neighbor-address
> Fix RegEx for xpath leaf-list keys which include a "-" character.

- gnoi_cert/gnoi_cert.go
The current client doesn't allow loading multiple certificates at once in a single install/rotate operation. 
New argument: `other_cas`
Comma separated list of filename prefixes that the client will use to the load the associated `.pem` and `.key` files
Usage:
```
./gnoi_cert -target_addr localhost:9339 -target_name 10.85.68.161 -logtostderr -ca device_rootCA.pem -ca_key device_rootCA.key -op provision -cert_id gnoi_demo \
-other_cas client_intermediateCA_B,client_intermediateCA_C,client_rootCA_B,client_rootCA_C,device_intermediateCA,device_rootCA -ip_address 10.85.68.161 -organization gnoi_dem -time_out 1m
```
> allow loading multiple CAs into bundle

- oc_config_validate/README.md
- oc_config_validate/demo/results.json
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/models/versions
- oc_config_validate/oc_config_validate/schema.py
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/update_models.sh
It is important to know against which OC models were the JSON blobs in tests compared.
When binding the OC models, a file is written with the versions of the models. This file is used to print the OC models versions and also added to the results.
> oc_config_validate prints and reports the OC models versions used.

- oc_config_validate/README.md
- oc_config_validate/demo/tests.yaml
- oc_config_validate/docs/tests.md
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/context.py
- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/oc_config_validate/target.py
- oc_config_validate/oc_config_validate/testbase.py
There can be none, one or more initial configurations to set before a test. These are pairs of xpath and json file, and they can be defined in the test YAML file and also as command argument.
In this process, some code used go rearranged, mainly out of the main function into other modules.
> Multiple initial configurations

- .gitignore
- utils/credentials/credentials.go
- utils/credentials/credentials_test.go
This ensures that the same context being called twice by `AttachToContext` doesn't replicate the username and password metadata.
Possibly addresses #271.
> Override username and password instead of appending them.

- oc_config_validate/README.md
- oc_config_validate/demo/run_demo.sh
- oc_config_validate/demo/tests.yaml
- oc_config_validate/docs/tests.md
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/context.py
- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/oc_config_validate/target.py
- oc_config_validate/oc_config_validate/testbase.py
This allows for a self-contained test file, with the option to override some of the targe options from the command line.
> Define Target in test file, and override options with command arguments

- oc_config_validate/oc_config_validate/.gitignore
- oc_config_validate/oc_config_validate/models/versions
- oc_config_validate/oc_config_validate/update_models.sh
- oc_config_validate/tests/system.yaml
The System OC model was missing the hostname leaf when binded along all other models.
Also, ignoring the generated Python files from Git.
> OC system model bindings built separately

- oc_config_validate/docs/testcases.md
- oc_config_validate/docs/testclasses.md
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/testcases/config_state.py
- oc_config_validate/oc_config_validate/testcases/get.py
- oc_config_validate/oc_config_validate/testcases/setget.py
- oc_config_validate/tests/system.yaml
Some testcases were doing retry already, with fixed retries and delays. But some devices need more time to process certain OC configurations and reflect them on gNMI Gets. So now the basic testcases support defining retries when needed.
This is also a good indication of how long a Configuration Management systems needs to wait/retry before validating a configuration has been processed.
> Add retries for testcases that validate or compare after gNMI Sets

- oc_config_validate/oc_config_validate/testbase.py
This avoids the surfacing a long and verbose exception stack.
> ValueErrors raised when binding are caught.

- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/oc_config_validate/testbase.py
The tests take long time, there is little benefit in using msec resolution.
> Use seconds to measure test durations.

- oc_config_validate/README.md
- oc_config_validate/demo/tests.yaml
- oc_config_validate/docs/tests.md
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/context.py
- oc_config_validate/oc_config_validate/target.py
Targets needs some time to process configuation after a successful gNMI
Set request.
Also, correcting lint errors in .md files, and puntuation in help
messages in the command line.
> Add cooldown delay after gNMI Set

- oc_config_validate/README.md
- oc_config_validate/docs/testcases.md
- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/models/versions
- oc_config_validate/oc_config_validate/testbase.py
- oc_config_validate/oc_config_validate/update_models.sh
This allows oc_config_validate to check agains any OC model and gNMI xpath (no more need to maintain a list of models and binding instructions).
> Create Python bindings for all public OC models

- gnmi_get/gnmi_get.go
- gnmi_set/gnmi_set.go
1. Add -prefix parameter to gnmi_set.
2. Add -prefix and -data_type to gnmi_get.
data_type can be 0 (ALL), 1 (CONFIG), 2 (STATE) 3 (OPERATIONAL). Default is 0.
prefix is a string that can be used in GNMI Get/Set messages. Default is none.
> Support for -prefix and -data_type in gnmi_get and -prefix for gnmi_set.

- oc_config_validate/oc_config_validate/runner.py
Useful when the testscases are run externally by a unittest.TestRunner.
> Add an auxiliary method to get all TestSuites.

- oc_config_validate/demo/Dockerfile
- oc_config_validate/demo/README.md
- oc_config_validate/demo/run_demo.sh
- oc_config_validate/docker/Dockerfile
- oc_config_validate/docker/README.md
This allows to easily run the Demo without installing anything on the 
host.
Also, this could facilitate the use of oc_config_validate in 
Docker-based environments.
The Demo script was updated to run correctly inside a container
> Add Docker images.

- oc_config_validate/demo/results.json
- oc_config_validate/docs/testclasses.md
- oc_config_validate/oc_config_validate/testcases/config_state.py
- oc_config_validate/oc_config_validate/testcases/get.py
- oc_config_validate/oc_config_validate/testcases/set.py
- oc_config_validate/oc_config_validate/testcases/setget.py
Based on usage, it makes more sense for the basic testcases to be atomic, one single test method that reflects better the sequential nature of the tests.
> Make the basic testacases atomic.

- utils/xpath/xpath.go
When accessing SONiC openconfig paths SONiC requires the `openconfig-*: ` prefix.  The regex change doesn't require that but allows for the `:` to denote it.  
== GetRequest:
prefix: <
origin: "OC-YANG"
>
path: <
elem: <
name: **"openconfig-interfaces:interfaces"**
>
elem: <
name: "interface"
key: <
key: "name"
value: "Ethernet0"
>
>
>
encoding: JSON_IETF
> allow for SONiC style path root

- oc_config_validate/oc_config_validate/__main__.py
- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/oc_config_validate/testbase.py
Instead of a binary result, failing to apply an init config raises an Exception that can be caught and better exposed on calling methods.
> [oc_config_validate] Raise Exception when failed to load init config

- oc_config_validate/docs/testclasses.md
- oc_config_validate/oc_config_validate/testcases/telemetry_once.py
- oc_config_validate/oc_config_validate/testcases/telemetry_sample.py
- oc_config_validate/tests/ap_telemetry.yaml
Add testcases to oc_config_validate to test Stream Subscriptions rendering the path in an OC Model.
This does not need to tell the number of expected updates, but an OC model represented by the path, and all Leafs are checked.
> oc_config_validate Stream Subscription model-based tests

- oc_config_validate/docs/testclasses.md
- oc_config_validate/oc_config_validate/runner.py
- oc_config_validate/oc_config_validate/schema.py
- oc_config_validate/oc_config_validate/target.py
- oc_config_validate/oc_config_validate/testcases/telemetry_once.py
- oc_config_validate/oc_config_validate/testcases/telemetry_sample.py
- oc_config_validate/py_tests/test_schema.py
* Send a single SubscribeRequest with many paths is sent.
* Do path inclusion comparison deal with sorted keys.
* Compare Subscription Update paths with requested paths.
* Check paths in Subscription tests.
> [oc_config_validate] Improve Subscription tests with multiple paths

- oc_config_validate/docs/vendor_testing.md
These guidelines describe suggested best practices vendors can use oc_config_validate in a collaborative fashion with customers.
> Creates guidelines for vendors

- gnmi/server.go
- gnmi/server_test.go
Similar to STREAM Subscription, a Server produces 1 Notification message per Subscription in a ONCE Subscription.
This makes the behavior of both methods similar, and increases code reuse.
> ONCE produces 1 Notification per Subscription.

- oc_config_validate/requirements.txt
The bindings in oc_config_validate break with pyangbind>=0.8.3, due to https://github.com/robshakir/pyangbind/pull/297 (the current bindings import `bitarray`, which pyangbind >= 0.8.3 removed).
This commit enforces a dependency on the pyangbind version for the current code to work. In a future commit, the bindings and this dependency will be updated.
> Indicate that the code needs pyangbind<0.8.3

- oc_config_validate/docs/custom_model.md
- oc_config_validate/docs/oc_models.md
Goes through a simple example of using a custom binding with vendor augments
> [oc_config_validate] Add custom model documentation

- oc_config_validate/oc_config_validate/testcases/telemetry_sample.py
To better show that the test is about measuring the time interval between received Subcription Updates
From `Update timestamps for ... out of interval: [0, 29968248320, 31000567808] diff in nsecs` to  `Subscribe updates for ... received  out of sample interval 3 secs, received updates intervals: [2.996824832, 3.1000567808]`
@xavier-contreras
> Improve Log message for Subscribe Tests
